modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]
modId="hot_iron"
version="1.0.4"
displayName="Hot Iron"
displayURL="https://www.curseforge.com/minecraft/mc-mods/hot-iron"
logoFile="logo.png"
credits="Created with a help of MCreator"
authors="Regen__"
description="A mod that makes process of creating tools and armors much more interactive"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.hot_iron]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.hot_iron]]
    modId="jei"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration